environment:
  domain: "dockerlab.local"
  masterip: "10.10.10.11"
  base_box: "ubuntu/xenial64"

boxes:
- name: "k8-1"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1524"
  cpu: "1"

- name: "k8-2"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

#- name: "k8-3"
#  mgmt_ip: "10.10.10.13"
#  hostonly_ip: "192.168.56.13"
#  mem: "1524"
#  cpu: "1"
#
#- name: "k8-4"
#  mgmt_ip: "10.10.10.14"
#  hostonly_ip: "192.168.56.12"
#  mem: "1524"
#  cpu: "1"
