environment:
  domain: "dockerlab.local"
  masterip: "10.10.10.11"
  base_box: "frjaraur/xenial64"
  base_box_version: "1.4"
  engine_version: "17.03.2~ce-0~ubuntu-xenial"
  kubernetes_version: "1.10.0-00"
  calico_url: "https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml"
  kubernetes_token: "auxpg8.c64z4cmf9iutpef6"
boxes:
- name: "k8s-1"
  role: "master"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "3072"
  cpu: "2"

- name: "k8s-2"
  role: "worker"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

- name: "k8s-3"
  role: "worker"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"
#
#- name: "k8-4"
#  role: "worker"
#  mgmt_ip: "10.10.10.14"
#  hostonly_ip: "192.168.56.14"
#  mem: "1524"
#  cpu: "1"
#
#- name: "k8-client"
#  role: "client"
#  mgmt_ip: "10.10.10.15"
#  hostonly_ip: "192.168.56.15"
#  mem: "1024"
#  cpu: "1"

