kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    stream-snippets: |
      resolver kube-dns.kube-system.svc.cluster.local valid=5s;

      upstream unbound-udp {
          zone unbound-udp 64k;
          server unbound-svc.default.svc.cluster.local service=_dns._udp resolve;
      }

      server {
          listen 5353 udp;
          proxy_pass unbound-udp;
          proxy_responses 1;
          status_zone unbound-udp;
      }

      upstream unbound-tcp {
          zone unbound-tcp 64k;
          server unbound-svc.default.svc.cluster.local service=_dns-tcp._tcp resolve;
      }

      server {
          listen 5353;
          proxy_pass unbound-tcp;
          status_zone unbound-tcp;
      } 