apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colors-ingress
#  namespace: kong
#  annotations:
#    rate-limiting.plugin.konghq.com: |
#      add-ratelimiting-to-route
spec:
  rules:
  - host: blue.example.com
    http:
      paths:
      - backend:
          serviceName: blue-svc
          servicePort: 80
  - host: red.example.com
    http:
      paths:
      - backend:
          serviceName: red-svc
          servicePort: 80
